### PR TITLE
Add support for python2.7

### PR DESCRIPTION
**Pull request by uda**
Just by using python2.7's style super() I was able to this in 2.7

### CODE REVIEW

**Comment by oz123** [comment]
Is it really necessary? IMHO python 2 should be gone...

**Comment by stzr1123** [comment]
I think the same. Encourage discontinuation of 2

**Comment by uda** [comment]
I agree this is the ideal, and i assumed that was the purpose of not putting any work in support.
But I do work on a system that is written for 2.7, and currently refactoring to have it work on 3.x is too expensive, and I do believe other developers find themselves in the same position.
So IMHO, if it doesn't add complication to the library, just a syntax change, why not? It's not that the library uses `F""` templates and typing

**Comment by oz123** [comment]
@uda, These are valid points, but they work as well backward. I refuse to add python 2 support because it might prevent me from using features of 3.x later.

**Comment by uda** [comment]
I won't say I am happy... but since we both agree on the ideal, I understand your choice.

**Comment by oz123** [comment]
@uda Never the less, thank you for contributing and stepping forward. I am surprised how many people find this little library useful!

**Pull request closed without merging**
