### PR TITLE
Add Python 2 support

### PR DESCRIPTION
**Pull request by jaydg**

### CODE REVIEW

**Comment by oz123** [comment]
Hi,
Thank you for the PR!
Please  see this https://github.com/mobilityhouse/ttldict/pull/4

**Comment by jaydg** [comment]
Too bad. I shall look for an alternative..

**Comment by oz123** [comment]
You can still patch your own Version and even install directly from GitHub. Merging your PR only means that the package is available on pypi.

**Comment by jaydg** [comment]
Yes, the latter was the plan 😁

**Pull request closed without merging**
